import Head from "next/head";
import Dropdown from "../../components/dropdown/Dropdown";



export default function Home() {

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen top-[12rem] bg-[#020410]" >
        
       <section className="pt-[3.5rem] ">
        <Dropdown/>
       </section>
      </main>
    </>
  );
}
