import Head from "next/head";
import {useEffect} from "react";
import { Inter } from "next/font/google";
import Dashboard from "../../components/schoolmanagementsystem/Dashboard";

import AOS from "aos";
import "aos/dist/aos.css";
import Students from "../../components/schoolmanagementsystem/Students";


export default function Home() {

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen top-[12rem]">
        
       <section className="pt-[3.5rem] ">
       <Dashboard/>
       <Students/>
       </section>
      </main>
    </>
  );
}
