import Head from "next/head";
import {useEffect} from "react";
import { Inter } from "next/font/google";
import Hero from "@/components/portfolio/Hero";
import Skills from "@/components/portfolio/Skills";
import Services from "@/components/portfolio/Services";
import Projects from "@/components/portfolio/Projects";
import Testimonial from "@/components/portfolio/Testimonial";
import Hireme from "@/components/portfolio/Hireme";
import Contact from "@/components/portfolio/Contact";
import AOS from "aos";
import "aos/dist/aos.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // useEffect(() => {
  //  AOS.init({
  //   duration:1800,
  //   offset:100
  //  });
  // }, [])
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" pt-5 ">
        <section className=" pt-[3.5rem]">
          <Hero />
        </section>

        <Skills />
        <Services />
        <Projects />
        <Testimonial />
        <Hireme />
        <Contact />
       
        <footer className="py-3 text-center">
          <h6 className="font-Paprika font-bold text-[#253D57] leading-8 mb-3">
            ZIA ULLAH
          </h6>
          <p className="text-[0.95rem] text-dark_primary font-[poppins] loading-7">
            &copy; {new Date().getFullYear()} Ziaullah All Rights reserved
          </p>
        </footer>
      </main>
    </>
  );
}
