import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import Portfolio from "../components/Portfolio";
import { useEffect } from "react";
import Hero from "../components/Hero";
import Bot from "../components/Bot"
import About from "../components/About";
import Skills from "../components/Skills";
import Hireme from "../components/Hireme";
import Project from "../components/Project";
import Contact from "../components/Contact";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {


 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-slate-800 pt-5 ">
        <Bot/>
        <section className="flex items-center justify-center top-0 pt-20  bg-gray-800">
          <Hero/>
        </section>
        <About/>
        <Skills/>
        <Hireme/>
        {/* <section className="mt-10 flex">
        </section> */}
        <Project/>
        <Contact/>
        
      </main>
    </>
  );
}
